name: "Update Warps"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

permissions:
  contents: write

env:
  message: "update"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.13.1
      - run: "node warp-data/get-warp-data.js"
      - run: echo "message=Warp update @ $(date +%Y%m%dT%H:%M:%S%Z)" >> "$GITHUB_ENV"
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          default_author: github_actions
          message: ${{ env.message }}
